import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/herencia-polimorfismo.html.vue"
const data = JSON.parse("{\"path\":\"/blog/article/herencia-polimorfismo.html\",\"title\":\"Herencia y polimorfismo: un enfoque práctico y comparativo entre Java y Django\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"Herencia y polimorfismo: un enfoque práctico y comparativo entre Java y Django\",\"date\":\"2025-10-03T00:00:00.000Z\",\"category\":[\"Blog\"],\"tag\":[\"Programacion\",\"Herencia\",\"Polimorfismo\"],\"type\":\"article\",\"description\":\"Herencia y polimorfismo: un enfoque práctico y comparativo entre Java y Django Introducción En el marco de una organización sin ánimo de lucro (ONG) como myOng, la gestión de pr...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Herencia y polimorfismo: un enfoque práctico y comparativo entre Java y Django\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2025-10-03T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/article/herencia-polimorfismo.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Herencia y polimorfismo: un enfoque práctico y comparativo entre Java y Django\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Herencia y polimorfismo: un enfoque práctico y comparativo entre Java y Django Introducción En el marco de una organización sin ánimo de lucro (ONG) como myOng, la gestión de pr...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Polimorfismo\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Herencia\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Programacion\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-10-03T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":3.38,\"words\":1014},\"filePathRelative\":\"blog/article/herencia-polimorfismo.md\",\"excerpt\":\"\\n<h2>Introducción</h2>\\n<p>En el marco de una organización sin ánimo de lucro (ONG) como <em>myOng</em>, la gestión de <strong>proyectos</strong> puede adquirir múltiples formas.<br>\\nAlgunos proyectos se centran en la <strong>modificación de estatutos</strong>, donde varios socios colaboran con una fecha tope y documentación asociada; otros son <strong>proyectos de actividades</strong>, donde uno o varios socios presentan una propuesta, se vota, se aprueba un presupuesto y se lleva a cabo, generando finalmente una memoria de ejecución y gastos.</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
