<template><div><h1 id="introduccion-a-los-algoritmos" tabindex="-1"><a class="header-anchor" href="#introduccion-a-los-algoritmos"><span>Introducción a los Algoritmos,</span></a></h1>
<h2 id="tutorial-1-–-notas" tabindex="-1"><a class="header-anchor" href="#tutorial-1-–-notas"><span>Tutorial 1 – Notas</span></a></h2>
<h3 id="los-enteros" tabindex="-1"><a class="header-anchor" href="#los-enteros"><span>Los enteros</span></a></h3>
<p>Comenzaremos nuestro estudio de los algoritmos observando aquellos que trabajan con enteros. Distinguimos:</p>
<p><code v-pre>Z = { ..., -2, -1, 0, 1, 2, ... }</code> : el conjunto de todos los enteros</p>
<p><code v-pre>N = { 0, 1, 2, ... }</code> : el conjunto de los números naturales</p>
<p><code v-pre>{ 1, 2, ... }</code> : los enteros positivos</p>
<p>El estudio matemático de los enteros se denomina <strong>teoría de números</strong>.</p>
<hr>
<h3 id="division-entera" tabindex="-1"><a class="header-anchor" href="#division-entera"><span>División entera</span></a></h3>
<p>Un resultado básico de la teoría elemental de números es el <strong>teorema de la división</strong>:</p>
<p>Para cualquier entero <code v-pre>a</code> y cualquier entero <code v-pre>b &gt; 0</code>, existen enteros únicos <code v-pre>q</code> y <code v-pre>r</code>, con <code v-pre>0 ≤ r &lt; b</code>, tales que</p>
<p><code v-pre>a = q · b + r</code></p>
<p>Dados <code v-pre>a</code> y <code v-pre>b</code>, las funciones <strong>div</strong> (división entera) y <strong>mod</strong> (resto entero) calculan los valores <code v-pre>q</code> y <code v-pre>r</code>. Escribimos:</p>
<p><code v-pre>q = a div b</code> (el cociente)<br>
<code v-pre>r = a mod b</code> (el resto)</p>
<p>Así, para todos los enteros <code v-pre>a</code> y <code v-pre>b</code> con <code v-pre>b &gt; 0</code>:</p>
<p><code v-pre>a = (a div b) · b + (a mod b</code></p>
<p>Por ejemplo:</p>
<ul>
<li>Si <code v-pre>a = 17</code> y <code v-pre>b = 3</code>, entonces <code v-pre>q = a div b = 5</code> y <code v-pre>r = a mod b = 2</code>, porque <code v-pre>17 = 5 · 3 + 2</code>.</li>
<li>Si <code v-pre>a = -17</code> y <code v-pre>b = 3</code>, entonces <code v-pre>q = a div b = -6</code> y <code v-pre>r = a mod b = 1</code>, porque <code v-pre>-17 = -6 · 3 + 1</code>.</li>
</ul>
<p>En Python, el operador <code v-pre>//</code> realiza la división entera y el operador <code v-pre>%</code> calcula el resto. Así:</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">17</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> //</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> ==</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 5</span></span>
<span class="line"><span style="--shiki-light:#986801;--shiki-dark:#D19A66">17</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> %</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> ==</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 2</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">-</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">17</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> //</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> ==</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> -</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">6</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">-</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66">17</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> %</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> ==</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 1</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Observa que si <code v-pre>a</code> es divisible exactamente por <code v-pre>b</code>, entonces el resto después de dividir es 0. Por tanto, podemos comprobar si <code v-pre>b</code> divide a <code v-pre>a</code> verificando el resto. En Python, por ejemplo:</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">input</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'Enter n: '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">if</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">%</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 7</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> ==</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">  print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(n, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'is divisible by 7'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">else</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">  print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(n, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'is not divisible by 7'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="horas-minutos-y-segundos" tabindex="-1"><a class="header-anchor" href="#horas-minutos-y-segundos"><span>Horas, minutos y segundos</span></a></h3>
<p>Hay <code v-pre>60 · 60 · 24 = 86,400</code> segundos en un día. Supongamos que se nos da un entero <code v-pre>0 ≤ t &lt; 86,400</code> que representa el número de segundos desde medianoche. Queremos calcular el número de horas, minutos y segundos desde medianoche, obteniendo una hora como <code v-pre>3:24:54</code>.</p>
<p>En otras palabras, queremos encontrar enteros <code v-pre>0 ≤ h &lt; 24</code>, <code v-pre>0 ≤ m &lt; 60</code> y <code v-pre>0 ≤ s &lt; 60</code> tales que</p>
<p>t = 3600 h + 60 m + s</p>
<p>¿Cómo hacerlo? Una forma es calcular primero el número de horas: <code v-pre>h = t // 3600</code>. Luego <code v-pre>t % 3600</code> es el número de segundos restantes tras quitar las <code v-pre>h</code> horas. Esto se implementa en Python así:</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">input</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'How many seconds? '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">hours </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">//</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3600</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">%</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 3600</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">mins </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">//</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">secs </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">%</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(hours, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">':'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, mins, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">':'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, secs)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Otra forma posible es calcular primero los segundos: <code v-pre>s = t % 60</code>. Luego <code v-pre>t // 60</code> es el número de minutos que quedan tras quitar los <code v-pre>s</code> segundos. En Python:</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">input</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'How many seconds? '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">secs </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">%</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">//</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span><span style="--shiki-light:#A0A1A7;--shiki-light-font-style:italic;--shiki-dark:#7F848E;--shiki-dark-font-style:italic">  # ahora t es el total de minutos</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">mins </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">%</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">hours </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> t </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">//</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 60</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(hours, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">':'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, mins, </span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">':'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, secs)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="representacion-decimal" tabindex="-1"><a class="header-anchor" href="#representacion-decimal"><span>Representación decimal</span></a></h3>
<p>Por convención, usamos la <strong>representación decimal (base 10)</strong> al escribir números en la vida cotidiana. Cuando escribimos un número como <code v-pre>1985</code>, en realidad queremos decir una suma de potencias de 10:</p>
<p>1985 = 1 · 10³ + 9 · 10² + 8 · 10 + 5</p>
<p>Ahora discutiremos algoritmos simples que pueden descomponer un entero (por ejemplo, 1985) en una serie de dígitos decimales (1, 9, 8, 5), y combinar una serie de dígitos decimales en un entero.</p>
<h3 id="separar-en-digitos" tabindex="-1"><a class="header-anchor" href="#separar-en-digitos"><span>Separar en dígitos</span></a></h3>
<p>Para separar en dígitos, primero observamos que para cualquier entero <code v-pre>i</code>:</p>
<ul>
<li><code v-pre>i % 10</code> es el último dígito de <code v-pre>i</code></li>
<li><code v-pre>i // 10</code> es el número formado por todos los dígitos de <code v-pre>i</code> excepto el último</li>
</ul>
<p>Podemos verlo matemáticamente factorizando la expansión de 1985:</p>
<p>1985 = 1 · 10³ + 9 · 10² + 8 · 10 + 5 = 10 (1 · 10² + 9 · 10 + 8) + 5</p>
<p>De esta factorización es evidente que <code v-pre>1985 % 10 = 5</code> y <code v-pre>1985 // 10 = (1 · 10² + 9 · 10 + 8) = 198</code>.</p>
<p>Así que podemos escribir un bucle simple que extrae los dígitos de un entero sucesivamente. En Python:</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">input</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'Enter n: '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">while</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">></span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  d </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">%</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">//</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">  print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'digit: '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, d)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Por cierto, observa la similitud de este problema con el ejercicio anterior sobre las horas. La hora <code v-pre>3:24:54</code> son <code v-pre>12,294</code> segundos después de medianoche, ya que</p>
<p>12,294 = 3 · 60² + 24 · 60 + 54</p>
<p>Así que una hora como <code v-pre>3:24:54</code> es en realidad como un número escrito en base 60. (Si esto no está claro, no te preocupes: pronto hablaremos de bases distintas a la base 10).</p>
<hr>
<h3 id="combinar-digitos" tabindex="-1"><a class="header-anchor" href="#combinar-digitos"><span>Combinar dígitos</span></a></h3>
<p>Para combinar una serie de dígitos en un número, observamos primero que podemos <strong>añadir un dígito decimal d a un entero n</strong> usando esta fórmula:</p>
<p>n' = 10 n + d</p>
<p>Por ejemplo, si <code v-pre>n = 198</code> y <code v-pre>d = 5</code>, entonces <code v-pre>n' = 10 · 198 + 5 = 1985</code>.</p>
<p>Así que podemos escribir un bucle simple que lea una serie de dígitos y los combine en un entero. En Python:</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">while</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> True</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  d </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">input</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'Digit: '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">  if</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> d </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">&#x3C;</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">    break</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> *</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">+</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> d</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'n is'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, n)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>El programa se comporta así:</p>
<div class="language- line-numbers-mode" data-highlighter="shiki" data-ext="" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-"><span class="line"><span>$ py joinDigits.py</span></span>
<span class="line"><span>Digit: 1</span></span>
<span class="line"><span>Digit: 9</span></span>
<span class="line"><span>Digit: 8</span></span>
<span class="line"><span>Digit: 5</span></span>
<span class="line"><span>Digit: -1</span></span>
<span class="line"><span>n is 1985</span></span>
<span class="line"><span></span></span>
<span class="line"><span>$</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>Como señalaron algunos estudiantes, podemos reescribir el bucle anterior sin <code v-pre>break</code> (aunque al coste de realizar una multiplicación innecesaria):</p>
<div class="language-python line-numbers-mode" data-highlighter="shiki" data-ext="python" style="--shiki-light:#383A42;--shiki-dark:#abb2bf;--shiki-light-bg:#FAFAFA;--shiki-dark-bg:#282c34"><pre class="shiki shiki-themes one-light one-dark-pro vp-code" v-pre=""><code class="language-python"><span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">d </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span></span>
<span class="line"><span style="--shiki-light:#A626A4;--shiki-dark:#C678DD">while</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> d </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">>=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 0</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">:</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#986801;--shiki-dark:#D19A66"> 10</span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2"> *</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> n </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">+</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF"> d</span></span>
<span class="line"><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">  d </span><span style="--shiki-light:#383A42;--shiki-dark:#56B6C2">=</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2"> int</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">input</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'Digit: '</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">))</span></span>
<span class="line"><span style="--shiki-light:#0184BC;--shiki-dark:#56B6C2">print</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">(</span><span style="--shiki-light:#50A14F;--shiki-dark:#98C379">'n is'</span><span style="--shiki-light:#383A42;--shiki-dark:#ABB2BF">, n)</span></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


