import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/python-patterns.html.vue"
const data = JSON.parse("{\"path\":\"/blog/article/python-patterns.html\",\"title\":\"Patrones en Python\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"Patrones en Python\",\"date\":\"2025-10-02T00:00:00.000Z\",\"category\":[\"Blog\"],\"tag\":[\"Python\",\"Patterns\"],\"type\":\"article\",\"description\":\"Listado de patrones implementados en Python 1. Patrón Singlenton SinglentonSinglenton 2. Patrón Factoria FactoriaFactoria 3. Patrón Decorador DecoratorDecorator 4. Patrón Adapta...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Patrones en Python\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern1.jpeg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern2.jpeg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern3.jpeg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern4.jpeg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern5.jpeg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern6.jpeg\\\"],\\\"datePublished\\\":\\\"2025-10-02T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/blog/article/python-patterns.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Patrones en Python\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"Listado de patrones implementados en Python 1. Patrón Singlenton SinglentonSinglenton 2. Patrón Factoria FactoriaFactoria 3. Patrón Decorador DecoratorDecorator 4. Patrón Adapta...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/images/blog/Pattern1.jpeg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Patterns\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"Python\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-10-02T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":0.19,\"words\":56},\"filePathRelative\":\"blog/article/python-patterns.md\",\"excerpt\":\"\\n<h2>1. Patrón Singlenton</h2>\\n<figure><img src=\\\"/images/blog/Pattern1.jpeg\\\" alt=\\\"Singlenton\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>Singlenton</figcaption></figure>\\n<h2>2. Patrón Factoria</h2>\\n<figure><img src=\\\"/images/blog/Pattern2.jpeg\\\" alt=\\\"Factoria\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>Factoria</figcaption></figure>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
