import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/03-MVC-patrones.html.vue"
const data = JSON.parse("{\"path\":\"/docencia/dam-daw/DWES/03-MVC-patrones.html\",\"title\":\"UT03 MVC y otros patrones\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"UT03 MVC y otros patrones\",\"date\":\"2025-09-01T00:00:00.000Z\",\"icon\":\"gear\",\"description\":\"UT03 MVC y otros patrones 1. Introducción En ingeniería del software, como en cualquier otra ingeniería, existen una serie de soluciones estandarizadas que se ajustan sorprenden...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"UT03 MVC y otros patrones\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-2-niveles.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-N-niveles.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-3-capas.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-mvc.png\\\"],\\\"datePublished\\\":\\\"2025-09-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docencia/dam-daw/DWES/03-MVC-patrones.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"UT03 MVC y otros patrones\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"UT03 MVC y otros patrones 1. Introducción En ingeniería del software, como en cualquier otra ingeniería, existen una serie de soluciones estandarizadas que se ajustan sorprenden...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-09-01T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":17.7,\"words\":5310},\"filePathRelative\":\"docencia/dam-daw/DWES/03-MVC-patrones.md\",\"excerpt\":\"\\n<!-- ![En construcción](/images/under-construction.jpg) -->\\n<h2>1. Introducción</h2>\\n<p>En ingeniería del software, como en cualquier otra ingeniería, existen una serie de soluciones estandarizadas que se ajustan sorprendentemente bien a una enorme variedad de situaciones diferentes.<br>\\nEstas soluciones se denominan <strong>patrones de software</strong>, y vamos a empezar este tema hablando de ellas.</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
