import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/03-MVC-patrones.html.vue"
const data = JSON.parse("{\"path\":\"/docencia/dam-daw/DWES/03-MVC-patrones.html\",\"title\":\"UT03 MVC y otros patrones\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"UT03 MVC y otros patrones\",\"date\":\"2025-09-01T00:00:00.000Z\",\"icon\":\"gear\",\"description\":\"UT03 MVC y otros patrones En construcciónEn construcción En este tema trabajaremos los siguientes RAs: RA5. Desarrolla aplicaciones Web identificando y aplicando mecanismos para...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"UT03 MVC y otros patrones\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-2-niveles.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-N-niveles.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-3-capas.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/03-arquitectura-mvc.png\\\"],\\\"datePublished\\\":\\\"2025-09-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docencia/dam-daw/DWES/03-MVC-patrones.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"UT03 MVC y otros patrones\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"UT03 MVC y otros patrones En construcciónEn construcción En este tema trabajaremos los siguientes RAs: RA5. Desarrolla aplicaciones Web identificando y aplicando mecanismos para...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-09-01T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":17.81,\"words\":5344},\"filePathRelative\":\"docencia/dam-daw/DWES/03-MVC-patrones.md\",\"excerpt\":\"\\n<figure><img src=\\\"/images/under-construction.jpg\\\" alt=\\\"En construcción\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>En construcción</figcaption></figure>\\n<!--  -->\\n<blockquote>\\n<p><strong>En este tema trabajaremos los siguientes RAs:</strong></p>\\n<ul>\\n<li>RA5. Desarrolla aplicaciones Web identificando y aplicando mecanismos para separar el código de presentación de la lógica de negocio.</li>\\n</ul>\\n</blockquote>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
