import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/04-persistencia-datos.html.vue"
const data = JSON.parse("{\"path\":\"/docencia/dam-daw/DWES/04-persistencia-datos.html\",\"title\":\"UT04 Persistencia de datos\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"UT04 Persistencia de datos\",\"date\":\"2025-09-29T00:00:00.000Z\",\"icon\":\"database\",\"description\":\"UT04 Persistencia de datos En construcciónEn construcción 1. La capa de persistencia de datos La capa de persistencia en una aplicación sirve de puente entre la compleja lógica ...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"UT04 Persistencia de datos\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/banner02.webp\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\\\"],\\\"datePublished\\\":\\\"2025-09-29T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docencia/dam-daw/DWES/04-persistencia-datos.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"UT04 Persistencia de datos\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"UT04 Persistencia de datos En construcciónEn construcción 1. La capa de persistencia de datos La capa de persistencia en una aplicación sirve de puente entre la compleja lógica ...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/banner02.webp\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-09-29T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":15.31,\"words\":4592},\"filePathRelative\":\"docencia/dam-daw/DWES/04-persistencia-datos.md\",\"excerpt\":\"<!-- ![banner](/images/dwes/banner02.webp)-->\\n<h1>UT04 Persistencia de datos</h1>\\n<figure><img src=\\\"/images/under-construction.jpg\\\" alt=\\\"En construcción\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>En construcción</figcaption></figure>\\n<h2>1. La capa de persistencia de datos</h2>\\n<p>La <strong>capa de persistencia</strong> en una aplicación sirve de puente entre la compleja lógica de negocio de una aplicación y el almacén de datos subyacente, que a menudo es una base de datos relacional. Las decisiones que se tomen en esta capa repercuten a lo largo de toda la vida útil del software, influyendo en su rendimiento, mantenibilidad y adaptabilidad. Para abordar este desafío, debemos navegar entre los dos paradigmas principales en la persistencia.</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
