import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/06-cookies-y-seguridad.html.vue"
const data = JSON.parse("{\"path\":\"/docencia/dam-daw/DWES/06-cookies-y-seguridad.html\",\"title\":\"UT06 Cookies y Seguridad en aplicaciones web\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"UT06 Cookies y Seguridad en aplicaciones web\",\"date\":\"2025-10-01T00:00:00.000Z\",\"icon\":\"fluent:cookies-16-filled\",\"description\":\"UT06 Cookies y Seguridad en aplicaciones web En construcciónEn construcción En este capítulo vamos a profundizar en varios aspectos de vital importancia para las aplicaciones we...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"UT06 Cookies y Seguridad en aplicaciones web\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/jwt01.jpg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/jwt02.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/tsl.png\\\"],\\\"datePublished\\\":\\\"2025-10-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docencia/dam-daw/DWES/06-cookies-y-seguridad.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"UT06 Cookies y Seguridad en aplicaciones web\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"UT06 Cookies y Seguridad en aplicaciones web En construcciónEn construcción En este capítulo vamos a profundizar en varios aspectos de vital importancia para las aplicaciones we...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/images/under-construction.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-10-01T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":8.06,\"words\":2418},\"filePathRelative\":\"docencia/dam-daw/DWES/06-cookies-y-seguridad.md\",\"excerpt\":\"\\n<figure><img src=\\\"/images/under-construction.jpg\\\" alt=\\\"En construcción\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>En construcción</figcaption></figure>\\n<!--  -->\\n<p>En este capítulo vamos a profundizar en varios aspectos de vital importancia para las aplicaciones web.</p>\\n<p>Por un lado, tenemos las cookies y las sesiones, dos mecanismos que permiten a la aplicación mantener vivas algunas variables de forma indefinida.</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
