import comp from "/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/0X1-seguridad.html.vue"
const data = JSON.parse("{\"path\":\"/docencia/dam-daw/DWES/0X1-seguridad.html\",\"title\":\"UTX0 Cookies y Seguridad en aplicaciones web\",\"lang\":\"es-ES\",\"frontmatter\":{\"title\":\"UTX0 Cookies y Seguridad en aplicaciones web\",\"date\":\"2025-09-01T00:00:00.000Z\",\"icon\":\"gear\",\"description\":\"UTX0 Cookies y Seguridad en aplicaciones web En este capítulo vamos a profundizar en varios aspectos de vital importancia para las aplicaciones web. Por un lado, tenemos las coo...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"UTX0 Cookies y Seguridad en aplicaciones web\\\",\\\"image\\\":[\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/jwt01.jpg\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/jwt02.png\\\",\\\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/tsl.png\\\"],\\\"datePublished\\\":\\\"2025-09-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"darioaxel\\\",\\\"url\\\":\\\"darioaxel.dev\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docencia/dam-daw/DWES/0X1-seguridad.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"darioaxel\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"UTX0 Cookies y Seguridad en aplicaciones web\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"UTX0 Cookies y Seguridad en aplicaciones web En este capítulo vamos a profundizar en varios aspectos de vital importancia para las aplicaciones web. Por un lado, tenemos las coo...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/images/dwes/jwt01.jpg\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"es-ES\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2025-09-01T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":8.03,\"words\":2409},\"filePathRelative\":\"docencia/dam-daw/DWES/0X1-seguridad.md\",\"excerpt\":\"\\n<p>En este capítulo vamos a profundizar en varios aspectos de vital importancia para las aplicaciones web.</p>\\n<p>Por un lado, tenemos las cookies y las sesiones, dos mecanismos que permiten a la aplicación mantener vivas algunas variables de forma indefinida.</p>\\n<p>Después estudiaremos un problema endémico a las aplicaciones web: la seguridad. En efecto, al tratarse de aplicaciones que, por definición, están permanentemente conectadas a la red, son susceptibles de recibir ataques de manera continua e indiscriminada. Y, de hecho, lo hacen. Veremos cuáles son los tipos de ataque más frecuente y cómo podemos proteger nuestra aplicación contra ellos, algo en lo que juegan un papel importante las cookies y las variables de sesión.</p>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
