<template><div><h1 id="_1-modelos-de-datos" tabindex="-1"><a class="header-anchor" href="#_1-modelos-de-datos"><span>1. Modelos de datos</span></a></h1>
<p>El modelado de datos es el primer paso para diseñar las bases de datos, y sirve de puente entre el mundo real y el modelo de base de datos que reside en el ordenador. Desempeña un papel fundamental ya que reduce las complejidades del mundo real y las convierte en abstracciones más fáciles de entender.</p>
<p>Un <a href="https://www.fpvirtualaragon.es/pluginfile.php/68126/mod_resource/content/0/index.html#te59a3a37-68ee-fe81-1557-6c439de07008" target="_blank" rel="noopener noreferrer">modelo de datos</a> es la representación relativamente simple, generalmente gráfica, de estructuras de datos complejas del mundo real. Con relación a las bases de datos un modelo representa estructuras de datos y sus características, relaciones, restricciones y transformaciones.</p>
<p>Un buen diseño de la base de datos es el fundamento de buenas aplicaciones, y un buen diseño se inicia con la construcción de un buen modelo.</p>
<h2 id="_1-1-evolucion-de-los-sistemas-de-almacenamiento-de-la-informacion" tabindex="-1"><a class="header-anchor" href="#_1-1-evolucion-de-los-sistemas-de-almacenamiento-de-la-informacion"><span>1.1. <strong>Evolución de los sistemas de almacenamiento de la información.</strong></span></a></h2>
<h1 id="_2-modelo-entidad-relacion" tabindex="-1"><a class="header-anchor" href="#_2-modelo-entidad-relacion"><span>2. Modelo Entidad-Relación</span></a></h1>
<p>El <strong>modelo Entidad/Relación</strong>  lo introdujo Peter Chen en 1976 y se trata de un modelo conceptual que permite representar el mundo real mediante una serie de símbolos y expresiones determinados. El modelo de datos <strong>Entidad/Relación (E/R , ER ó E-R)</strong> está basado en una percepción consistente en objetos básicos llamados <strong>entidades</strong> y las <strong>relaciones</strong>  entre estos objetos. Con el paso del tiempo, este modelo ha sufrido modificaciones y mejoras. Actualmente, el modelo <strong>Entidad/Relación Extendido</strong> (<strong>ERE</strong>) es el más aceptado, aunque existen variaciones que hacen que este modelo no sea totalmente un estándar. Ambos modelos serán estudiados a lo largo de esta unidad.</p>
<p>El modelo Entidad/Relación es una herramienta de referencia para la representación conceptual de problemas del mundo real. Su objetivo principal es facilitar el diseño de bases de datos permitiendo la especificación de un esquema que representa la estructura lógica completa de una base de datos. Este esquema partirá de las descripciones textuales de la realidad, que establecen los requerimientos del sistema, buscando ser lo más fiel posible al comportamiento del mundo real para modelarlo.</p>
<p>El modelo de datos E/R representa el significado de los datos, es un modelo semántico. De ahí que no esté orientado a ningún sistema físico concreto y tampoco tiene un ámbito informático puro de aplicación, ya que podría utilizarse para describir procesos de producción, estructuras de empresa, etc. Además, las características actuales de este modelo favorecen la representación de cualquier tipo de sistema y a cualquier nivel de abstracción o refinamiento, lo cual da lugar a que se aplique tanto a la representación de problemas que vayan a ser tratados mediante un sistema informatizado, como manual.</p>
</div></template>


