export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/index.html.js"), meta: {"title":"Home","icon":"house"} }],
  ["/portfolio.html", { loader: () => import(/* webpackChunkName: "portfolio.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/portfolio.html.js"), meta: {"title":"Portfolio Home","icon":"house"} }],
  ["/blog/", { loader: () => import(/* webpackChunkName: "blog_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/index.html.js"), meta: {"title":"","icon":"note"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"title":"Features demo","icon":"laptop-code"} }],
  ["/demo/disable.html", { loader: () => import(/* webpackChunkName: "demo_disable.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/demo/disable.html.js"), meta: {"title":"Disabling layout and features","icon":"gears","order":4} }],
  ["/demo/encrypt.html", { loader: () => import(/* webpackChunkName: "demo_encrypt.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/demo/encrypt.html.js"), meta: {"title":"Encryption Article","icon":"lock"} }],
  ["/demo/layout.html", { loader: () => import(/* webpackChunkName: "demo_layout.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/demo/layout.html.js"), meta: {"title":"Layout","icon":"object-group","order":2} }],
  ["/demo/markdown.html", { loader: () => import(/* webpackChunkName: "demo_markdown.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/demo/markdown.html.js"), meta: {"title":"Markdown Enhance","icon":"fa6-brands:markdown","order":2} }],
  ["/demo/page.html", { loader: () => import(/* webpackChunkName: "demo_page.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/demo/page.html.js"), meta: {"title":"Page Config","icon":"file","order":3} }],
  ["/docencia/", { loader: () => import(/* webpackChunkName: "docencia_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/index.html.js"), meta: {"title":"Docencia","icon":"lightbulb"} }],
  ["/guide/", { loader: () => import(/* webpackChunkName: "guide_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/guide/index.html.js"), meta: {"title":"Guide","icon":"lightbulb"} }],
  ["/blog/article/adaptacion-theme-hope.html", { loader: () => import(/* webpackChunkName: "blog_article_adaptacion-theme-hope.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/adaptacion-theme-hope.html.js"), meta: {"date":1750636800000,"category":["Blog"],"tag":["Vue","Nuxt","Theme Hope"],"excerpt":"\n<h2>Descripción del Proyecto</h2>\n<p>Este proyecto es una API RESTful desarrollada con Django y PostgreSQL para el testeo de futuros<br>\nusos en los módulos.</p>\n<h2>Software a utilizar</h2>\n<ul>\n<li>Python: 3.11 (última estable)</li>\n<li>Django: 5.2.3 (última estable, requiere Python ≥3.10)</li>\n<li>PostgreSQL: 17 (última estable, disponible como imagen oficial en Docker)</li>\n<li>Poetry: para gestión de dependencias y entorno virtual</li>\n<li>Docker y Docker Compose: para contenerización</li>\n</ul>","readingTime":{"minutes":0.48,"words":145},"title":"Adaptación de Theme Hope para mi Blog","type":"article"} }],
  ["/blog/article/django-rest-api-docker.html", { loader: () => import(/* webpackChunkName: "blog_article_django-rest-api-docker.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/django-rest-api-docker.html.js"), meta: {"date":1750377600000,"category":["Blog"],"tag":["Docker","Django","API Rest","Python"],"excerpt":"\n<h2>Descripción del Proyecto</h2>\n<p>Este proyecto es una API RESTful desarrollada con Django y PostgreSQL para el testeo de futuros<br>\nusos en los módulos.</p>\n<h2>Software a utilizar</h2>\n<ul>\n<li>Python: 3.11 (última estable)</li>\n<li>Django: 5.2.3 (última estable, requiere Python ≥3.10)</li>\n<li>PostgreSQL: 17 (última estable, disponible como imagen oficial en Docker)</li>\n<li>Poetry: para gestión de dependencias y entorno virtual</li>\n<li>Docker y Docker Compose: para contenerización</li>\n</ul>","readingTime":{"minutes":0.67,"words":200},"title":"Creación de una API REST con Django y Docker","type":"article"} }],
  ["/blog/article/first-article.html", { loader: () => import(/* webpackChunkName: "blog_article_first-article.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/first-article.html.js"), meta: {"date":1750377600000,"category":["Blog"],"tag":["VuePress","JavaScript"],"excerpt":"\n<p>¡Hola, mundo! Este es mi primer artículo en VuePress con Theme Hope 😃<br>\nPara comenzar, voy a explicar todos los pasos que he ido dando para crear esta web y como configurarla.</p>\n<h2>Instalación de VuePress con Theme Hope</h2>\n<h2>Estructura del Proyecto</h2>\n<h2>Modificaciones en el Theme</h2>","readingTime":{"minutes":0.22,"words":67},"title":"Mi primer artículo!!","type":"article"} }],
  ["/docencia/asir/", { loader: () => import(/* webpackChunkName: "docencia_asir_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/index.html.js"), meta: {"title":"CFGS ASIR","icon":"laptop-code"} }],
  ["/docencia/dam-daw/", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/index.html.js"), meta: {"title":"CFGS DAM/DAW","icon":"laptop-code"} }],
  ["/guide/bar/", { loader: () => import(/* webpackChunkName: "guide_bar_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/guide/bar/index.html.js"), meta: {"title":"Bar feature","icon":"lightbulb"} }],
  ["/guide/bar/baz.html", { loader: () => import(/* webpackChunkName: "guide_bar_baz.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/guide/bar/baz.html.js"), meta: {"title":"Baz","icon":"circle-info"} }],
  ["/guide/foo/", { loader: () => import(/* webpackChunkName: "guide_foo_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/guide/foo/index.html.js"), meta: {"title":"Foo feature","icon":"lightbulb"} }],
  ["/guide/foo/ray.html", { loader: () => import(/* webpackChunkName: "guide_foo_ray.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/guide/foo/ray.html.js"), meta: {"title":"Ray","icon":"circle-info"} }],
  ["/docencia/asir/gestionbasesdatos/98-creditos-reconocimientos.html", { loader: () => import(/* webpackChunkName: "docencia_asir_gestionbasesdatos_98-creditos-reconocimientos.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/gestionbasesdatos/98-creditos-reconocimientos.html.js"), meta: {"title":"Créditos y reconocimientos","icon":"circle-info","order":-1} }],
  ["/docencia/asir/gestionbasesdatos/99-bibliografia.html", { loader: () => import(/* webpackChunkName: "docencia_asir_gestionbasesdatos_99-bibliografia.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/gestionbasesdatos/99-bibliografia.html.js"), meta: {"title":"Bibliografía","icon":"circle-info","order":-5} }],
  ["/docencia/asir/admonsgbd/1-conceptos-bbdd.html", { loader: () => import(/* webpackChunkName: "docencia_asir_admonsgbd_1-conceptos-bbdd.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/admonsgbd/1-conceptos-bbdd.html.js"), meta: {"title":"UT00 Conceptos básicos","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/asir/admonsgbd/2-instalacion-bbdd.html", { loader: () => import(/* webpackChunkName: "docencia_asir_admonsgbd_2-instalacion-bbdd.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/admonsgbd/2-instalacion-bbdd.html.js"), meta: {"title":"UT01 Instalación y configuración de SGBD","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/asir/admonsgbd/3-optimizacion-y-monitorizacion.html", { loader: () => import(/* webpackChunkName: "docencia_asir_admonsgbd_3-optimizacion-y-monitorizacion.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/admonsgbd/3-optimizacion-y-monitorizacion.html.js"), meta: {"title":"UT02 Optimización y monitorización","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/asir/admonsgbd/98-creditos-reconocimientos.html", { loader: () => import(/* webpackChunkName: "docencia_asir_admonsgbd_98-creditos-reconocimientos.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/admonsgbd/98-creditos-reconocimientos.html.js"), meta: {"title":"Créditos y reconocimientos","icon":"circle-info","order":-1} }],
  ["/docencia/asir/admonsgbd/99-bibliografia.html", { loader: () => import(/* webpackChunkName: "docencia_asir_admonsgbd_99-bibliografia.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/admonsgbd/99-bibliografia.html.js"), meta: {"title":"Bibliografía","icon":"circle-info","order":-5} }],
  ["/docencia/asir/admonsgbd/", { loader: () => import(/* webpackChunkName: "docencia_asir_admonsgbd_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/admonsgbd/index.html.js"), meta: {"title":"CFGS Administración de Sistemas Gestores de Bases de Datos","icon":"laptop-code"} }],
  ["/docencia/dam-daw/DWES/00-introduccion.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_00-introduccion.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/00-introduccion.html.js"), meta: {"title":"UT00 Introducción","icon":"rocket"} }],
  ["/docencia/dam-daw/DWES/01-arquitecturas-web.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_01-arquitecturas-web.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/01-arquitecturas-web.html.js"), meta: {"title":"UT01 Arquitecturas Web","icon":"gears"} }],
  ["/docencia/dam-daw/DWES/02-lenguajesdwes.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_02-lenguajesdwes.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/02-lenguajesdwes.html.js"), meta: {"title":"UT02 Lenguajes de programación en entorno servidor","icon":"circle-info"} }],
  ["/docencia/dam-daw/DWES/0X1-seguridad.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_0X1-seguridad.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/0X1-seguridad.html.js"), meta: {"title":"UTX0 Cookies y Seguridad en aplicaciones web","icon":"gear"} }],
  ["/docencia/dam-daw/DWES/0X2-servicios.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_0X2-servicios.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/0X2-servicios.html.js"), meta: {"title":"UTX02 Servicios REST","icon":"gear"} }],
  ["/docencia/dam-daw/DWES/98-creditos-reconocimientos.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_98-creditos-reconocimientos.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/98-creditos-reconocimientos.html.js"), meta: {"title":"Créditos y reconocimientos","icon":"cib:creative-commons","order":-1} }],
  ["/docencia/dam-daw/DWES/99-bibliografia.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_99-bibliografia.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/99-bibliografia.html.js"), meta: {"title":"Bibliografía","icon":"material-symbols:local-library-outline","order":-5} }],
  ["/docencia/dam-daw/DWES/", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/index.html.js"), meta: {"title":"Desarrollo Web Entorno Servidor (DWES)","icon":"laptop-code"} }],
  ["/docencia/dam-daw/basesdatos/0-introduccion.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_0-introduccion.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/0-introduccion.html.js"), meta: {"title":"UT00 Introducción","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/dam-daw/basesdatos/1-sistemas-de-ficheros.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_1-sistemas-de-ficheros.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/1-sistemas-de-ficheros.html.js"), meta: {"title":"UT01 Sistemas de Ficheros","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/dam-daw/basesdatos/2-1-algebra-relacional.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_2-1-algebra-relacional.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/2-1-algebra-relacional.html.js"), meta: {"title":"UT02.1 Álgebra relacional","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/dam-daw/basesdatos/2-diseno-logico.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_2-diseno-logico.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/2-diseno-logico.html.js"), meta: {"title":"UT02 Diseño lógico de Bases de Datos","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/dam-daw/basesdatos/3-diseno-fisico.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_3-diseno-fisico.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/3-diseno-fisico.html.js"), meta: {"title":"UT03 Diseño físico de Bases de Datos","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/dam-daw/basesdatos/4-realizacion-consultas.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_4-realizacion-consultas.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/4-realizacion-consultas.html.js"), meta: {"title":"UT04 Realización de consultas","icon":"material-symbols:book-5-outline"} }],
  ["/docencia/dam-daw/basesdatos/5-tratamiento-datos.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_5-tratamiento-datos.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/5-tratamiento-datos.html.js"), meta: {"title":"Tema 5: Tratamiento de datos"} }],
  ["/docencia/dam-daw/basesdatos/98-creditos-reconocimientos.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_98-creditos-reconocimientos.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/98-creditos-reconocimientos.html.js"), meta: {"title":"Créditos y reconocimientos","icon":"cib:creative-commons","order":-1} }],
  ["/docencia/dam-daw/basesdatos/99-bibliografia.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_99-bibliografia.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/99-bibliografia.html.js"), meta: {"title":"Bibliografía","icon":"material-symbols:local-library-outline","order":-5} }],
  ["/docencia/dam-daw/basesdatos/", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/index.html.js"), meta: {"title":"Bases Datos","icon":"laptop-code"} }],
  ["/docencia/dam-daw/DWES/Ejercicios/UT00-intruccion.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_Ejercicios_UT00-intruccion.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/Ejercicios/UT00-intruccion.html.js"), meta: {"title":"Ejercicios UT00. Introducción","icon":"pen"} }],
  ["/docencia/dam-daw/basesdatos/Ejercicios/UT01-sistemas-de-ficheros.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_Ejercicios_UT01-sistemas-de-ficheros.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/Ejercicios/UT01-sistemas-de-ficheros.html.js"), meta: {"title":"Ejercicios UT01. Sistemas de Ficheros","icon":"circle-info"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/blog/article/", { loader: () => import(/* webpackChunkName: "blog_article_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/index.html.js"), meta: {"title":"Artículos","index":false} }],
  ["/docencia/asir/gestionbasesdatos/", { loader: () => import(/* webpackChunkName: "docencia_asir_gestionbasesdatos_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/asir/gestionbasesdatos/index.html.js"), meta: {"title":"Gestionbasesdatos"} }],
  ["/docencia/dam-daw/DWES/Ejercicios/", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_Ejercicios_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/Ejercicios/index.html.js"), meta: {"title":"Ejercicios"} }],
  ["/docencia/dam-daw/basesdatos/Ejercicios/", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_basesdatos_Ejercicios_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/basesdatos/Ejercicios/index.html.js"), meta: {"title":"Ejercicios"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"Categoría","index":false} }],
  ["/category/blog/", { loader: () => import(/* webpackChunkName: "category_blog_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/category/blog/index.html.js"), meta: {"title":"Blog Categoría","index":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"Etiquetas","index":false} }],
  ["/tag/vue/", { loader: () => import(/* webpackChunkName: "tag_vue_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/vue/index.html.js"), meta: {"title":"Etiquetas: Vue","index":false} }],
  ["/tag/nuxt/", { loader: () => import(/* webpackChunkName: "tag_nuxt_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/nuxt/index.html.js"), meta: {"title":"Etiquetas: Nuxt","index":false} }],
  ["/tag/theme-hope/", { loader: () => import(/* webpackChunkName: "tag_theme-hope_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/theme-hope/index.html.js"), meta: {"title":"Etiquetas: Theme Hope","index":false} }],
  ["/tag/docker/", { loader: () => import(/* webpackChunkName: "tag_docker_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/docker/index.html.js"), meta: {"title":"Etiquetas: Docker","index":false} }],
  ["/tag/django/", { loader: () => import(/* webpackChunkName: "tag_django_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/django/index.html.js"), meta: {"title":"Etiquetas: Django","index":false} }],
  ["/tag/api-rest/", { loader: () => import(/* webpackChunkName: "tag_api-rest_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/api-rest/index.html.js"), meta: {"title":"Etiquetas: API Rest","index":false} }],
  ["/tag/python/", { loader: () => import(/* webpackChunkName: "tag_python_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/python/index.html.js"), meta: {"title":"Etiquetas: Python","index":false} }],
  ["/tag/vuepress/", { loader: () => import(/* webpackChunkName: "tag_vuepress_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/vuepress/index.html.js"), meta: {"title":"Etiquetas: VuePress","index":false} }],
  ["/tag/javascript/", { loader: () => import(/* webpackChunkName: "tag_javascript_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/tag/javascript/index.html.js"), meta: {"title":"Etiquetas: JavaScript","index":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"title":"Estrella","index":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"Línea de tiempo","index":false} }],
  ["/blog/article/", { loader: () => import(/* webpackChunkName: "blog_article_index.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/blog/article/index.html.js"), meta: {"title":"Artículos","index":false} }],
  ["/docencia/dam-daw/DWES/Pr%C3%A1cticas/UT00-intruccion.html", { loader: () => import(/* webpackChunkName: "docencia_dam-daw_DWES_Prácticas_UT00-intruccion.html" */"/home/darioaxel/Proyectos/darioaxel.github.io/src/.vuepress/.temp/pages/docencia/dam-daw/DWES/Prácticas/UT00-intruccion.html.js"), meta: {"title":"Práctica UT01. Introducción","icon":"pen"} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
